[project]
name = "kestra-slackbot"
version = "0.1.0"
description = "Kestra Slackbot Tutorial"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "slack-bolt>=1.22.0",
]
